### PR TITLE
Make -> CMake, boost everywhere to be able to cross-compile on NIXPKG…

### PR DESCRIPTION
**Pull request by tex**
…S to MINGW.

```
grip-mingw.nix:
    1 (import <nixpkgs> {
    2   crossSystem = {
    3     # config = "i686-pc-mingw32"; # switch to this if we want 32-bit version
    4     config = "x86_64-pc-mingw32";
    5     libc = "msvcrt";
    6     platform = {};
    7   };
    8 }).grip
nix-build grip-mingw.nix


grip.nix:
{ stdenv, fetchFromGitHub, boost, windows, pkgconfig, cmake }:

stdenv.mkDerivation rec {
  name = "grip-${version}";
  version = "0.6";

  src = fetchFromGitHub {
    owner = "tex";
    repo = "grip";
    rev = "..."; # fill correct value
    sha256 = "..."; # fill correct value
  };

  nativeBuildInputs = [ pkgconfig cmake ];

  buildInputs = [ boost ];

  extension = if stdenv.hostPlatform.isWindows then ".exe" else "";

  installPhase = ''
    install -Dm 555 src/grip/egrip${extension} -t "$out/bin"
    install -Dm 555 src/grip/fgrip${extension} -t "$out/bin"
    install -Dm 555 src/grip/grip${extension} -t "$out/bin"
    install -Dm 555 src/gripgen/gripgen${extension} -t "$out/bin"
  '';

  meta = {
    description = "Fast, indexed regexp search over large file trees.";
    homepage = https://github.com/sc0ty/grip;
    license = stdenv.lib.licenses.gplv3;
    platforms = stdenv.lib.platforms.linux ++ stdenv.lib.platforms.windows;
  };
}
```

### CODE REVIEW

**Comment by tex** [comment]
It is crashing... Will debug it.

**Comment by sc0ty** [comment]
Thanks, but why boost?
It's written in C++11 specifically to have minimum number of dependencies. Right now on POSIX system you can build it with no extra libraries.
I could agree that it is better to have cmake than makefile, I've chosen the later only because I have no experience with writing CMakeLists.
I can accept usage of boost threads if we make it optional, enabled by some switch or cmake magic, with std::thread to be used when possible.

Alternatively it should be easy to rewrite gripgen to run in single thread. Right now one thread is reading file names from stdin and putting it to queue, and the second thread is consuming queue and doing real work. I made it this way to not block find (or whatever is producing input). Single threaded version would probably suffer performance-wise.

**Comment by tex** [comment]
So it is crashing because of %zu in prints... Replacing it to %u in prints fixes the crash and everything is all-right.

Sorry I should have explained more. I am using NixOs, there is possibilit to cross compile its packages. I created package for grip and cross compiled it to Windows. I want to use it on my company laptop and I prefer to compile my utilities after code review.

Trouble is that mingw-w64 on NixOs comes with default win32 implementation and not posix implementation. C++11 features (mutex, unique_pointer, thread) unfortunaltely use the posix implementaiton resulting that my compiler is unable to compile it. It complains that mutex, ... are not found during linking. Using boost threads allows to avoid that as boost detects enviroment and uses win32 or pthread on mingw-w64. And you use other boost libraries so you did not look like member of anti-boost camp :-).

I removed threading and speed is almost same (slight decrease).

**Comment by sc0ty** [comment]
Do you find out why it is crashing with %zu? It is modifier specifically for size_t type and I can't see any misuse here.

I understand your situation and I'm not against boost, but still I would like to have option to build it with posix only when it is possible.

About removal of threading, I should time it myself when I wrote it. Probably unnecessary over-engineered it.

**Comment by tex** [comment]
Well, not 100% sure, but googling told me the zu is c++11 or c99 and not supported by the mingw win32 (same as with std mutex, thread,...). It also indicates there is some Windows specific modifier and general concensus is to just cast to long long int and use lld or unsigned variant. I bet that zu is ignored and then when it comes to print the string it gets wrong argument and tries to dereference the value of size_t argument.

**Comment by tex** [comment]
Hi, are you considering to megre this pull request or is there anything you are strongly against?

**Comment by sc0ty** [comment]
Sorry, didn't have time to try it before.
First of all, it won't compile on my machine (Ubuntu 16.04 with GCC). It is lacking C++11 compiler switch, and this project is entirely based on this version of the standard. That's probably why printf with %z was crashing your build. And please don't try to rewrite it to C++0x, I choose this version consciously.
Secondly, I can't understand what is your problem with making some kind of switch of auto detection mechanism to allow it to be build without boost when possible. The code is already written. I understand that it will complicate CMakeLists somewhat, but in my opinion it is worth it.

**Comment by tex** [comment]
You were right, setting C++11 fixes the %zu issue. Can you try whether it builds now on your Ubuntu?

**Comment by tex** [comment]
Well, less code means less bugs. Since other boost libraries are already used why not use another one? Is the filesystem boos lib too big?

**Comment by sc0ty** [comment]
You forget to set c++11 flag in test. Also my cmake (version 3.5.1) is complaining about the name
```
CMake Error at src/test/CMakeLists.txt:8 (add_executable):
  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.


CMake Error at src/test/CMakeLists.txt:14 (target_link_libraries):
  Cannot specify link libraries for target "test" which is not built by this
  project.
```
So maybe rename it to tests.

**Comment by tex** [comment]
Try this please.

**Comment by sc0ty** [comment]
Thanks, it works now.

**Comment by tex** [comment]
Thanks! Going to push the package into NixPkgs.

**Pull request merged**
